// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class RecipeStep implements SupadartClass<RecipeStep> {
  final String id;
  final String recipeId;
  final int position;
  final String description;
  final bool isOptional;

  const RecipeStep({
    required this.id,
    required this.recipeId,
    required this.position,
    required this.description,
    this.isOptional = false,
  });

  static String get table_name => 'recipe_steps';
  static String get c_id => 'id';
  static String get c_recipeId => 'recipe_id';
  static String get c_position => 'position';
  static String get c_description => 'description';
  static String get c_isOptional => 'is_optional';

  static List<RecipeStep> converter(List<Map<String, dynamic>> data) {
    return data.map(RecipeStep.fromJson).toList();
  }

  static RecipeStep converterSingle(Map<String, dynamic> data) {
    return RecipeStep.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? recipeId,
    int? position,
    String? description,
    bool? isOptional,
  }) {
    return {
      'id': ?id,
      'recipe_id': ?recipeId,
      'position': ?position,
      'description': ?description,
      'is_optional': ?isOptional,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String recipeId,
    required int position,
    required String description,
    bool isOptional = false,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      position: position,
      description: description,
      isOptional: isOptional,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? recipeId,
    int? position,
    String? description,
    bool? isOptional,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      position: position,
      description: description,
      isOptional: isOptional,
    );
  }

  factory RecipeStep.fromJson(Map<String, dynamic> jsonn) {
    return RecipeStep(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      recipeId: jsonn['recipe_id'] != null ? jsonn['recipe_id'].toString() : '',
      position: jsonn['position'] != null
          ? int.parse(jsonn['position'].toString())
          : 0,
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : '',
      isOptional: jsonn['is_optional'] == true,
    );
  }

  static Object New({
    String? id,
    String? recipeId,
    int? position,
    String? description,
    bool? isOptional,
  }) {
    return {
      'id': ?id,
      'recipe_id': ?recipeId,
      'position': ?position,
      'description': ?description,
      'is_optional': ?isOptional,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      position: position,
      description: description,
      isOptional: isOptional,
    );
  }

  static const _unset = Object();
  RecipeStep copyWith({
    Object? id = _unset,
    Object? recipeId = _unset,
    Object? position = _unset,
    Object? description = _unset,
    Object? isOptional = _unset,
  }) {
    return RecipeStep(
      id: id == _unset ? this.id : id as String,
      recipeId: recipeId == _unset ? this.recipeId : recipeId as String,
      position: position == _unset ? this.position : position as int,
      description: description == _unset
          ? this.description
          : description as String,
      isOptional: isOptional == _unset ? this.isOptional : isOptional as bool,
    );
  }
}
